FROM amazoncorretto:17-al2023

RUN yum install -y --allowerasing tar gzip unzip zip git curl shadow-utils findutils && \
    curl -fsSL https://rpm.nodesource.com/setup_24.x | bash - && \
    yum install -y nodejs && \
    npm install -g @google/gemini-cli && \
    yum clean all

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG LANG=C.UTF-8

RUN if id -u $USERNAME >/dev/null 2>&1; then \
        usermod --uid $USER_UID --gid $USER_GID $USERNAME; \
    else \
        groupadd --gid $USER_GID $USERNAME && \
        useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash; \
    fi

USER $USERNAME
WORKDIR /home/$USERNAME
